#!/bin/bash
#Author: Kelvin
#Date: October 19 2020
#Description: modification of packages for Ubuntu
apt install wget -y
apt install net-tools -y
apt install sysstat -y
apt install finger -y
apt install gcc -y
apt install make -y
apt install python3 -y
apt install epel-release -y 
apt install git -y

echo "Packages successfully installed"